use_frameworks!

platform :ios, '10.0'

target 'FrameworkA_Objc_DependencyIssue_Example' do
  pod 'FrameworkA_Objc_DependencyIssue', :path => '../'

  target 'FrameworkA_Objc_DependencyIssue_Tests' do
    inherit! :search_paths

    
  end
end
